#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import os, sys
import argparse
import toml
import subprocess
from pathlib import Path
import struct
from zlib import crc32

g_ProjectPath = ''
g_BuildPath = ''
g_SdkPath = ''
g_CHeader = ''
g_ProjectName = ''
g_ToolBase = ''
g_SearchPaths = []
g_Verbose = False

defaultExeToml = """# This is a TOML document generated by MadBuild.

board = "SwiftIOBoard"
type = "executable"
dependencies = [
    "SwiftIO",
]"""

defaultLibToml = """# This is a TOML document generated by MadBuild.

board = "SwiftIOBoard"
type = "library"
dependencies = [
    "SwiftIO",
]"""

def quoteStr(path):
    return '"%s"' % str(path)

def generateToml(name, type):
    ret = sorted(Path('.').glob('*.mmswift'))

    if ret:
        print('Project ' + ret[0].name + ' already exist, initiaization failed!')
        os._exit(-1)

    Path('./' + name + '.mmswift').touch(exist_ok = True)
    if type == 'lib':
        Path('./' + name + '.mmswift').write_text(defaultLibToml)
        Path('./Sources/' + name + '/' + name + '.swift').touch(exist_ok = True)
    else:
        Path('./' + name + '.mmswift').write_text(defaultExeToml)
        Path('./Sources/' + name + '/main.swift').touch(exist_ok = True)


def initProject(args):
    if args.name:
        name = args.name
    else:
        name = Path('.').resolve().name

    src = Path('./Sources') / name
    src.mkdir(parents = True, exist_ok = True)
    generateToml(name, args.type)

    os._exit(0)


def parseTOML():
    ret = sorted(g_ProjectPath.glob('*.mmswift'))

    if ret:
        name = ret[0].stem
        tomlString = ret[0].read_text()
        if tomlString:
            try:
                tomlDic = toml.loads(tomlString)
            except:
                print('Project file ' + ret[0].name + ' decoding failed!')
                os._exit(-1)
        else:
            ret[0].write_text(defaultExeToml)
            tomlDic = toml.loads(defaultExeToml)
        tomlDic['name'] = name
        return tomlDic

    print('Error: Can not find project file!')
    os._exit(-1)
    

def cleanBuild():
    files =  sorted(g_BuildPath.glob('*.bin'))
    files += g_BuildPath.glob('*.elf')
    files += g_BuildPath.glob('*.map')
    files += g_BuildPath.glob('*.a')
    files += g_BuildPath.glob('*.o*')
    files += g_BuildPath.glob('*.c')
    files += g_BuildPath.glob('*.swiftmodule')
    files += g_BuildPath.glob('*.swiftdoc')
    for file in files:
        file.unlink()
    return


def getSDKTool(tool):
    value = ''
    if tool == 'swiftc':
        value = (g_SdkPath / g_ToolBase / 'toolchains/swift/bin/swiftc')
    elif tool == 'stdPath':
        value = (g_SdkPath / g_ToolBase / 'toolchains/swift/lib/swift/zephyr/thumbv7em')
    elif tool == 'ar':
        value = (g_SdkPath / g_ToolBase / 'toolchains/gcc/bin/arm-none-eabi-ar')
    elif tool == 'gcc':
        value = (g_SdkPath / g_ToolBase / 'toolchains/gcc/bin/arm-none-eabi-gcc')
    elif tool == 'gpp':
        value = (g_SdkPath / g_ToolBase / 'toolchains/gcc/bin/arm-none-eabi-g++')
    elif tool == 'objcopy':
        value = (g_SdkPath / g_ToolBase / 'toolchains/gcc/bin/arm-none-eabi-objcopy')
    elif tool == 'gen_isr_tables':
        value = (g_SdkPath / g_ToolBase / 'scripts/dist/gen_isr_tables/gen_isr_tables')
    elif tool == 'mm':
        value = (g_SdkPath / g_ToolBase / 'scripts/dist/mm/mm')
    return value


def resolveModule(modulePath, moduleName):
    ret = sorted(modulePath.glob(moduleName + '*'))
    if ret:
        realPath = ret[0]
    else:
        print("Can't find module " + moduleName)
        os._exit(-1)

    buildPath = realPath / '.build'

    if buildPath.exists():
        swiftModule = sorted(buildPath.glob(moduleName + '.swiftmodule'))
        staticLibrary = sorted(buildPath.glob('lib' + moduleName + '.a'))
        if swiftModule and staticLibrary:
            return buildPath

    print('Start to compile module: ' + moduleName)
    buildPath.mkdir(exist_ok = True)

    os.chdir(realPath)
    cmd = quoteStr(getSdkTool('mm'))
    cmd += ' --sdk ' + quoteStr(g_SdkPath)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    if p.poll():
        print('Compile ' + moduleName + ' failed!')
        os._exit(-1)
    return buildPath


def compileSwift(target):
    cmd = quoteStr(getSDKTool('swiftc'))

    swiftFlags = [
        '-module-name ' + g_ProjectName,
        '-target thumbv7em-none--eabi',
        '-target-cpu cortex-m7',
        '-target-fpu fpv5-dp-d16',
        '-float-abi soft',
        #'-parse-as-library',
        '-O',
        '-static-stdlib',
        '-function-sections',
        '-data-sections',
        '-Xcc -D__ZEPHYR__',
        '-Xfrontend -assume-single-threaded',
        '-no-link-objc-runtime'
    ]

    if target == 'module':
        swiftFlags.insert(0, '-parse-as-library')
        swiftFlags.insert(0, '-emit-module')
    elif target == 'object':
        swiftFlags.insert(0, '-parse-as-library')
        swiftFlags.insert(0, '-c')
    elif target == 'exe':
        swiftFlags.insert(0, '-c')
    else:
        os._exit(-1)

    if g_CHeader: 
        swiftFlags.append('-import-objc-header ' + quoteStr(g_CHeader))

    for item in g_SearchPaths:
        swiftFlags.append('-I ' + quoteStr(item))

    swiftFiles = sorted((g_ProjectPath / 'Sources' / g_ProjectName).rglob("*.swift"))
    for file in swiftFiles:
        swiftFlags.append(quoteStr(file))

    for item in swiftFlags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def mergeObjects():
    cmd = quoteStr(getSDKTool('ar'))

    arFlags = [
        '-rcs'
    ]

    targetName = quoteStr(g_BuildPath / ('lib' + g_ProjectName + '.a'))
    arFlags.append(targetName)

    files = sorted(g_BuildPath.glob("*.o"))
    for file in files:
        arFlags.append(quoteStr(file))

    for item in arFlags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def linkELF(step):
    cmd = quoteStr(getSDKTool('gpp'))

    flags = [
        '-mcpu=cortex-m7',
        '-mthumb',
        '-mfpu=fpv5-d16',
        '-mfloat-abi=soft',
        '-mabi=aapcs',
        '-nostdlib',
        '-static',
        '-no-pie',
        '-Wl,-u,_OffsetAbsSyms',
        '-Wl,-u,_ConfigAbsSyms',
        #'-Wl,--print-memory-usage',
        '-Wl,-X',
        '-Wl,-N',
        '-Wl,--gc-sections',
        '-Wl,--build-id=none',
        '-Wl,--sort-common=descending',
        '-Wl,--sort-section=alignment',
        '-Wl,--no-enum-size-warning',
        #'-Wl,--strip-all',
        #'-Wl,--orphan-handling=warn',
        #'-Wl,-Map=' + buildFolder + '/' + g_ProjectName + '.map',
        #halPath + '/generated/empty_file.c.obj'
    ]

    if step == 'step2':
        mapTarget = quoteStr(g_BuildPath / (g_ProjectName + '.map'))
        flags.append('-Wl,-Map=' + mapTarget)
        flags.append('-Wl,--print-memory-usage')
        linkScript = quoteStr(g_SdkPath / 'hal/HalSwiftIOBoard/generated/linker_pass_final.cmd')
        flags.append('-Wl,-T ' + linkScript)
        flags.append(quoteStr(g_BuildPath / 'isr_tables.c.obj'))
    elif step == 'step1':
        linkScript = quoteStr(g_SdkPath / 'hal/HalSwiftIOBoard/generated/linker.cmd')
        flags.append('-Wl,-T ' + linkScript)  
        flags.append(quoteStr(g_SdkPath / 'hal/HalSwiftIOBoard/generated/empty_file.c.obj'))
    
    flags.append('-L' + quoteStr(g_SdkPath / g_ToolBase / 'toolchains/gcc/arm-none-eabi/lib/thumb/v7e-m'))
    flags.append('-L' + quoteStr(g_SdkPath / g_ToolBase / 'toolchains/gcc/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m'))

    flags.append('-Wl,--whole-archive')
    flags.append(quoteStr(g_SdkPath / g_ToolBase / 'toolchains/swift/lib/swift/zephyr/thumbv7em/swiftrt.o'))
    flags.append(quoteStr(g_BuildPath / ('lib' + g_ProjectName + '.a')))

    librarFiles = sorted((g_SdkPath / 'hal/HalSwiftIOBoard/generated/whole').rglob("*.a"))
    for file in librarFiles:
        flags.append(quoteStr(file))

    flags.append('-Wl,--no-whole-archive')

    if step == 'step1':
        #g_SearchPaths.append(g_BuildPath)
        g_SearchPaths.append(g_SdkPath / 'hal/HalSwiftIOBoard/generated/no_whole')

    #print(g_SearchPaths)

    flags.append('-Wl,--start-group')
    for item in reversed(g_SearchPaths):
        files = sorted(item.glob("*.a"))
        for file in files:
            flags.append(quoteStr(file))
    
    flags += [
        #'-Wl,--start-group',
        '-lgcc',
        '-lstdc++',
        '-lm',
        '-lc',
        '-Wl,--end-group',
        '-o'
    ]

    if step == 'step1':
        flags.append(quoteStr(g_BuildPath / (g_ProjectName + '_prebuilt.elf')))
    elif step == 'step2':
        flags.append(quoteStr(g_BuildPath / (g_ProjectName + '.elf')))

    for item in flags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def generateIsr():
    cmd = quoteStr(getSDKTool('objcopy'))

    flags = [
        '-I elf32-littlearm',
        '-O binary',
        '--only-section=.intList',
        quoteStr(g_BuildPath / (g_ProjectName + '_prebuilt.elf')),
        'isrList.bin'
    ]

    for item in flags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def generateIsrTable():
    cmd = quoteStr(getSDKTool('gen_isr_tables'))

    flags = [
        '--output-source',
        'isr_tables.c',
        '--kernel ' + quoteStr(g_BuildPath / (g_ProjectName + '_prebuilt.elf')),
        '--intlist',
        'isrList.bin',
        '--sw-isr-table',
        '--vector-table'
    ]

    for item in flags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def compileIsr():
    cmd = quoteStr(getSDKTool('gcc'))

    includePath = [
        'hal/HalSwiftIOBoard/zephyr/include',
        'hal/HalSwiftIOBoard/zephyr/soc/arm/nxp_imx/rt',
        'hal/HalSwiftIOBoard/zephyr/lib/libc/newlib/include',
        'hal/HalSwiftIOBoard/zephyr/ext/hal/cmsis/Core/Include',
        'hal/HalSwiftIOBoard/modules/hal/nxp/mcux/devices/MIMXRT1052',
        'hal/HalSwiftIOBoard/modules/hal/nxp/mcux/drivers/imx',
        'hal/HalSwiftIOBoard/generated'
    ]

    flags = [
        '-DBOARD_FLASH_SIZE=CONFIG_FLASH_SIZE',
        '-DBUILD_VERSION=zephyr-v2.2.0',
        '-DCPU_MIMXRT1052DVL6B',
        '-DKERNEL',
        #'-DXIP_BOOT_HEADER_DCD_ENABLE=1',
        #'-DXIP_BOOT_HEADER_ENABLE=1',
        '-D_FORTIFY_SOURCE=2',
        '-D__LINUX_ERRNO_EXTENSIONS__',
        '-D__PROGRAM_START',
        '-D__ZEPHYR__=1',
        '-Os',
        '-ffreestanding',
        '-fno-common',
        '-g',
        '-mthumb',
        '-mcpu=cortex-m7',
        '-mfpu=fpv5-d16',
        '-mfloat-abi=soft',
        '-Wall',
        '-Wformat',
        '-Wformat-security',
        '-Wno-format-zero-length',
        '-Wno-main',
        '-Wno-pointer-sign',
        '-Wpointer-arith',
        '-Wno-unused-but-set-variable',
        '-Werror=implicit-int',
        '-fno-asynchronous-unwind-tables',
        '-fno-pie',
        '-fno-pic',
        '-fno-strict-overflow',
        '-fno-short-enums',
        '-fno-reorder-functions',
        '-fno-defer-pop',
        '-ffunction-sections',
        '-fdata-sections',
        '-mabi=aapcs',
        '-std=c99'
    ]

    for item in includePath:
        flags.append('-I' + quoteStr(g_SdkPath / item))
    
    flags.append('-isystem ' + quoteStr(g_SdkPath / g_ToolBase / 'toolchains/gcc/arm-none-eabi/include'))
    flags.append('-imacros ' + quoteStr(g_SdkPath / 'hal/HalSwiftIOBoard/generated/autoconf.h'))
    flags.append('-o ' + quoteStr(g_BuildPath / 'isr_tables.c.obj'))
    flags.append('-c ' + quoteStr(g_BuildPath / 'isr_tables.c'))

    for item in flags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def generateBin():
    cmd = quoteStr(getSDKTool('objcopy'))

    flags = [
        '-S',
        '-Obinary',
        '--gap-fill',
        '0xFF',
        '-R',
        '.comment',
        '-R',
        'COMMON',
        '-R',
        '.eh_frame'
    ]

    flags.append(quoteStr(g_BuildPath / (g_ProjectName + '.elf')))
    flags.append(quoteStr(g_BuildPath / (g_ProjectName + '.bin')))

    for item in flags:
        cmd += ' ' + item

    os.chdir(g_BuildPath)
    if g_Verbose:
        print(cmd)
    p = subprocess.Popen(cmd, shell = True)
    p.wait()
    return p.poll()


def int32_to_int8(n):
    mask = (1 << 8) - 1
    return [(n >> k) & mask for k in range(0, 32, 8)]


def addCrcToBin():
    data = (g_BuildPath / (g_ProjectName + '.bin')).read_bytes()
    value = crc32(data)
    list_dec = int32_to_int8(value)

    targetFile = (g_BuildPath / 'swiftio.bin')

    os.chdir(g_BuildPath)
    with open(targetFile, 'wb') as file:
        file.write(data)
        for number in list_dec:
            byte = struct.pack('B', number)
            file.write(byte)


def buildLibrary():
    if compileSwift('module'):
        os._exit(-1)
    if compileSwift('object'):
        os._exit(-1)
    if mergeObjects():
        os._exit(-1)

def buildExecutable():
    if compileSwift('exe'):
        os._exit(-1)
    if mergeObjects():
        os._exit(-1)
    if linkELF('step1'):
        os._exit(-1)
    if generateIsr():
        os._exit(-1)
    if generateIsrTable():
        os._exit(-1)
    if compileIsr():
        os._exit(-1)
    if linkELF('step2'):
        os._exit(-1)
    if generateBin():
        os._exit(-1)
    if addCrcToBin():
        os._exit(-1)
    return


def buildProject(args):
    global g_ProjectPath
    global g_BuildPath
    global g_SdkPath

    global g_SearchPaths

    global g_ProjectName
    global g_ToolBase
    global g_CHeader
    global g_Verbose

    g_ProjectPath = Path('.').resolve()
    g_BuildPath = Path('.build').resolve()
    g_SdkPath = Path(args.sdk).resolve()

    if args.verbose:
        g_Verbose = True

    if sys.platform.startswith('darwin'):
        g_ToolBase = 'tools_mac'
    elif sys.platform.startswith('win'):
        g_ToolBase = 'tools_win'
    elif sys.platform.startswith('linux'):
        g_ToolBase = 'tools_linux'

    if args.module:
        modulePath = Path(args.module).resolve()
    else:
        modulePath = (Path.home() / 'Documents' / 'MadMachine' / 'Library').resolve()

    # Parse name, type, dependencies
    tomlDic = parseTOML()
    g_ProjectName = tomlDic['name']
    if tomlDic.get('header'):
        g_CHeader = Path(tomlDic['header']).resolve()

    for moduleName in tomlDic['dependencies']:
        g_SearchPaths.append(resolveModule(modulePath, moduleName))

    g_SearchPaths.append(getSDKTool('stdPath'))

    g_BuildPath.mkdir(exist_ok = True)
    cleanBuild()

    if tomlDic['type'] == 'library':
        buildLibrary()
    elif tomlDic['type'] == 'executable':
        buildExecutable()


def parseArgs():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    initParser = subparsers.add_parser('init', help = 'Initiaize a new project. If not specified, project name depends on the current directory name')
    initParser.add_argument('-n', '--name', type = str, help = 'Initiaize a new project with a specified name')
    initParser.add_argument("-t", "--type", type = str, choices = ['exe', 'lib'], default = 'exe', help = "Project type, default type is executable")
    initParser.set_defaults(func = initProject)

    buildParser = subparsers.add_parser('build', help = 'Build a project, build type(executable/library) depends on the project file')
    buildParser.add_argument('--sdk', type = str, required = True, help = "SDK path")
    buildParser.add_argument('-m', '--module', type = str, help = "Swift module search path")
    buildParser.add_argument('-v', '--verbose', action = 'store_true', help = "Increase output verbosity")
    buildParser.set_defaults(func = buildProject)

    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    parseArgs()